name: Run Robot Framework Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-faker

    - name: Run Robot tests
      run: |
        robot --variable BROWSER:chrome --variable HEADLESS:True test_steps/

    - name: Upload Robot Framework reports
      uses: actions/upload-artifact@v4
      with:
        name: robot-report
        path: |
          output.xml
          report.html
          log.html